# Generated by Django 4.2.6 on 2023-10-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputdata",
            name="language",
            field=models.CharField(
                choices=[("English", "English"), ("Korean", "한국어")],
                default="English",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
    ]
