# Generated by Django 4.2.6 on 2023-10-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0002_alter_inputdata_language_delete_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputdata",
            name="end_time",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="inputdata",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ko", "한국어")],
                default="English",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inputdata",
            name="start_time",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
