# Generated by Django 4.2.6 on 2023-10-18 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InputData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.UUIDField(default=uuid.uuid4)),
                ("youtube_url", models.URLField()),
                ("start_time", models.CharField(blank=True, max_length=10)),
                ("end_time", models.CharField(blank=True, max_length=10)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("ko", "한국어")],
                        default="English",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
