# Generated by Django 4.2.6 on 2023-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transcribe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputdata",
            name="transcript",
            field=models.TextField(default=""),
        ),
    ]
