# Generated by Django 4.2.6 on 2023-10-18 09:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "transcribe",
            "0003_alter_inputdata_end_time_alter_inputdata_language_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputdata",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
